---
abstract: ~
author:
  - 'Matteo Corti <matteo@corti.li>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.18'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: check_rbl
no_index:
  directory:
    - inc
    - t
requires:
  Data::Validate::Domain: 0.12
  Data::Validate::IP: 0
  English: 0
  IO::Select: 0
  Monitoring::Plugin: 0
  Monitoring::Plugin::Getopt: 0
  Monitoring::Plugin::Threshold: 0
  Net::DNS: 0
  Readonly: 0
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 1.3.8
